#document settings
title: Test Pages
description: "DGU Test Pages"
url: http://datagovuk.github.io/testpages/
repo_name: testpages
branch: gh-pages

#global settings, no need to change these
root_url: http://datagovuk.github.io
org_name: datagovuk
prose_url: http://prose.io/
